#!/usr/bin/env python3
"""
HydroE2E 测试报告生成器
========================
复用 HydroClaw MDReporter，运行测试并生成详细 Markdown 报告 + HTML 预览。
"""

import sys
import time
import unittest
import traceback
import markdown
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any

# 复用 HydroClaw 的 MDReporter
sys.path.insert(0, str(Path("D:/research/HydroClaw")))
from tests.md_e2e.md_reporter import MDReporter, TestResult


# ---------------------------------------------------------------------------
# HTML 模板（含中文排版优化）
# ---------------------------------------------------------------------------

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{
    --bg: #ffffff; --fg: #1a1a2e; --accent: #0f3460;
    --green: #2ecc71; --red: #e74c3c; --yellow: #f39c12;
    --border: #e0e0e0; --code-bg: #f5f5f5; --table-stripe: #f9f9f9;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: "Microsoft YaHei", "PingFang SC", -apple-system, sans-serif;
    background: var(--bg); color: var(--fg);
    max-width: 960px; margin: 0 auto; padding: 2rem 2.5rem;
    line-height: 1.8;
  }}
  h1 {{ color: var(--accent); border-bottom: 3px solid var(--accent); padding-bottom: .5rem; margin: 1.5rem 0 1rem; font-size: 1.8rem; }}
  h2 {{ color: var(--accent); border-bottom: 1px solid var(--border); padding-bottom: .3rem; margin: 1.5rem 0 .8rem; font-size: 1.4rem; }}
  h3 {{ color: #333; margin: 1rem 0 .5rem; font-size: 1.15rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: .95rem; }}
  th {{ background: var(--accent); color: #fff; padding: .6rem .8rem; text-align: left; }}
  td {{ padding: .5rem .8rem; border-bottom: 1px solid var(--border); }}
  tr:nth-child(even) {{ background: var(--table-stripe); }}
  code {{ background: var(--code-bg); padding: .15rem .4rem; border-radius: 3px; font-size: .9em; }}
  pre {{ background: var(--code-bg); padding: 1rem; border-radius: 6px; overflow-x: auto; margin: 1rem 0; }}
  pre code {{ background: none; padding: 0; }}
  ul, ol {{ padding-left: 1.5rem; margin: .5rem 0; }}
  li {{ margin: .3rem 0; }}
  strong {{ color: var(--accent); }}
  .badge {{ display: inline-block; padding: .15rem .6rem; border-radius: 4px; font-weight: bold; font-size: .85rem; }}
  .badge-pass {{ background: #d4edda; color: #155724; }}
  .badge-fail {{ background: #f8d7da; color: #721c24; }}
  .badge-warn {{ background: #fff3cd; color: #856404; }}
  .summary-box {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 1rem; margin: 1rem 0;
  }}
  .summary-card {{
    background: var(--table-stripe); border: 1px solid var(--border);
    border-radius: 8px; padding: 1rem; text-align: center;
  }}
  .summary-card .number {{ font-size: 2rem; font-weight: bold; }}
  .summary-card .label {{ font-size: .85rem; color: #666; }}
  .pass .number {{ color: var(--green); }}
  .fail .number {{ color: var(--red); }}
  .warn .number {{ color: var(--yellow); }}
  .footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: .85rem; color: #999; text-align: center; }}
</style>
</head>
<body>
{body}
<div class="footer">
  Generated by HydroE2E × HydroClaw MDReporter &mdash; {timestamp}
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# 测试执行器
# ---------------------------------------------------------------------------

class DetailedTestRunner:
    """运行测试并收集详细结果。"""

    def __init__(self, test_module_path: str):
        self.test_module = test_module_path
        self.results: List[Dict[str, Any]] = []

    def run(self) -> Dict[str, Any]:
        """运行测试模块，返回结构化结果。"""
        loader = unittest.TestLoader()

        # 发现测试
        suite = loader.discover(
            start_dir=str(Path(self.test_module).parent),
            pattern=Path(self.test_module).name,
        )

        total_start = time.time()
        class_results = {}

        for test_group in suite:
            for test_case in test_group:
                if hasattr(test_case, '__iter__'):
                    for t in test_case:
                        self._run_single(t, class_results)
                else:
                    self._run_single(test_case, class_results)

        total_duration = time.time() - total_start

        # 汇总
        all_tests = []
        for cls_name, tests in class_results.items():
            all_tests.extend(tests)

        passed = sum(1 for t in all_tests if t["status"] == "PASSED")
        failed = sum(1 for t in all_tests if t["status"] == "FAILED")
        errors = sum(1 for t in all_tests if t["status"] == "ERROR")

        return {
            "module": self.test_module,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "duration": total_duration,
            "total": len(all_tests),
            "passed": passed,
            "failed": failed,
            "errors": errors,
            "class_results": class_results,
            "all_tests": all_tests,
        }

    def _run_single(self, test, class_results: dict):
        cls_name = test.__class__.__name__
        test_name = str(test).split()[0]
        doc = test.shortDescription() or ""

        if cls_name not in class_results:
            class_results[cls_name] = []

        start = time.time()
        result = unittest.TestResult()
        test.run(result)
        duration = time.time() - start

        if result.wasSuccessful():
            status = "PASSED"
            error_msg = None
        elif result.failures:
            status = "FAILED"
            error_msg = result.failures[0][1]
        elif result.errors:
            status = "ERROR"
            error_msg = result.errors[0][1]
        else:
            status = "FAILED"
            error_msg = "Unknown failure"

        class_results[cls_name].append({
            "name": test_name,
            "class": cls_name,
            "doc": doc,
            "status": status,
            "duration": duration,
            "error": error_msg,
        })


# ---------------------------------------------------------------------------
# 报告生成
# ---------------------------------------------------------------------------

def generate_detailed_report(run_result: dict, output_dir: Path) -> Path:
    """基于 HydroClaw MDReporter 生成详细测试报告。"""

    reporter = MDReporter()
    output_dir.mkdir(parents=True, exist_ok=True)

    # --- 构建 Markdown ---
    lines = []
    lines.append(f"# HydroE2E 测试报告: {Path(run_result['module']).stem}")
    lines.append("")

    # 概览卡片
    total = run_result["total"]
    passed = run_result["passed"]
    failed = run_result["failed"]
    errors = run_result["errors"]
    duration = run_result["duration"]
    pass_rate = (passed / total * 100) if total > 0 else 0

    lines.append("## 执行概览")
    lines.append("")
    lines.append(f"| 指标 | 值 |")
    lines.append(f"|------|-----|")
    lines.append(f"| **测试模块** | `{run_result['module']}` |")
    lines.append(f"| **执行时间** | {run_result['timestamp']} |")
    lines.append(f"| **总耗时** | {duration:.2f}s |")
    lines.append(f"| **测试总数** | {total} |")
    lines.append(f"| ✅ 通过 | {passed} ({pass_rate:.1f}%) |")
    lines.append(f"| ❌ 失败 | {failed} |")
    lines.append(f"| 💥 错误 | {errors} |")
    lines.append(f"| **通过率** | **{pass_rate:.1f}%** |")
    lines.append("")

    # 按测试类分组详情
    lines.append("## 详细结果")
    lines.append("")

    for cls_name, tests in run_result["class_results"].items():
        cls_passed = sum(1 for t in tests if t["status"] == "PASSED")
        cls_total = len(tests)
        cls_duration = sum(t["duration"] for t in tests)

        lines.append(f"### {cls_name}")
        lines.append(f"")
        lines.append(f"> {cls_passed}/{cls_total} 通过 · 耗时 {cls_duration:.3f}s")
        lines.append(f"")
        lines.append(f"| 状态 | 测试用例 | 说明 | 耗时 |")
        lines.append(f"|:----:|----------|------|-----:|")

        for t in tests:
            icon = "✅" if t["status"] == "PASSED" else ("❌" if t["status"] == "FAILED" else "💥")
            name = t["name"].replace("|", "\\|")
            doc = (t["doc"] or "-").replace("|", "\\|")
            lines.append(f"| {icon} | `{name}` | {doc} | {t['duration']*1000:.1f}ms |")

        lines.append("")

    # 失败详情
    failed_tests = [t for t in run_result["all_tests"] if t["status"] != "PASSED"]
    if failed_tests:
        lines.append("## 失败详情")
        lines.append("")
        for t in failed_tests:
            lines.append(f"### ❌ {t['name']}")
            lines.append(f"```")
            lines.append(t["error"] or "No error message")
            lines.append(f"```")
            lines.append("")

    # 性能分析
    lines.append("## 性能分析")
    lines.append("")

    all_tests = run_result["all_tests"]
    if all_tests:
        durations = [t["duration"] for t in all_tests]
        avg_duration = sum(durations) / len(durations)
        max_test = max(all_tests, key=lambda t: t["duration"])
        min_test = min(all_tests, key=lambda t: t["duration"])

        lines.append(f"| 指标 | 值 |")
        lines.append(f"|------|-----|")
        lines.append(f"| 平均耗时 | {avg_duration*1000:.1f}ms |")
        lines.append(f"| 最慢用例 | `{max_test['name']}` ({max_test['duration']*1000:.1f}ms) |")
        lines.append(f"| 最快用例 | `{min_test['name']}` ({min_test['duration']*1000:.1f}ms) |")
        lines.append(f"| 总吞吐量 | {total/duration:.1f} tests/s |")
        lines.append("")

        # Top 5 最慢
        lines.append("### 耗时 Top 5")
        lines.append("")
        lines.append("| 排名 | 测试用例 | 耗时 |")
        lines.append("|:----:|----------|-----:|")
        sorted_tests = sorted(all_tests, key=lambda t: t["duration"], reverse=True)
        for i, t in enumerate(sorted_tests[:5], 1):
            lines.append(f"| {i} | `{t['name']}` | {t['duration']*1000:.1f}ms |")
        lines.append("")

    # 测试覆盖的模块
    lines.append("## 覆盖模块")
    lines.append("")
    lines.append("本测试文件覆盖以下 HydroE2E 核心模块：")
    lines.append("")

    # 从测试类名推断覆盖模块
    module_map = {
        "TestSemanticInterpreter": ("hydroe2e.brain", "语义指令解析器"),
        "TestCanalPoolSimulator": ("hydroe2e.physics", "渠池水力学仿真"),
        "TestUniversalMPCSolver": ("hydroe2e.control", "MPC最优控制求解器"),
        "TestConfigManager": ("hydroe2e.config_manager", "YAML配置管理"),
        "TestSimulationDatabase": ("hydroe2e.database", "SQLite数据持久化"),
        "TestSimulationManager": ("hydroe2e.simulation_manager", "仿真编排器"),
        "TestExceptions": ("hydroe2e.exceptions", "自定义异常体系"),
        "TestMonitoringSystem": ("hydroe2e.monitor", "实时监控告警"),
    }

    lines.append("| 测试类 | 覆盖模块 | 功能 |")
    lines.append("|--------|----------|------|")
    for cls_name in run_result["class_results"]:
        if cls_name in module_map:
            mod, desc = module_map[cls_name]
            lines.append(f"| {cls_name} | `{mod}` | {desc} |")
        else:
            lines.append(f"| {cls_name} | - | - |")
    lines.append("")

    # 建议
    lines.append("## 改进建议")
    lines.append("")
    if pass_rate == 100:
        lines.append("- ✅ 所有测试通过，核心模块运行正常")
        lines.append("- 建议增加边界条件测试（极端水位、零流量）")
        lines.append("- 建议增加并发访问测试（数据库模块）")
        lines.append("- 建议添加性能基准回归测试")
    else:
        lines.append(f"- ⚠️ {failed + errors} 个测试未通过，请优先修复")
        lines.append("- 查看上方失败详情获取错误信息")
    lines.append("")

    # 写入 MD
    md_content = "\n".join(lines)
    md_path = output_dir / f"{Path(run_result['module']).stem}_report.md"
    md_path.write_text(md_content, encoding="utf-8")

    # 转 HTML
    html_body = markdown.markdown(
        md_content,
        extensions=["tables", "fenced_code", "codehilite"],
    )
    html_content = HTML_TEMPLATE.format(
        title=f"HydroE2E 测试报告 - {Path(run_result['module']).stem}",
        body=html_body,
        timestamp=run_result["timestamp"],
    )
    html_path = output_dir / f"{Path(run_result['module']).stem}_report.html"
    html_path.write_text(html_content, encoding="utf-8")

    print(f"✅ MD 报告:   {md_path}")
    print(f"✅ HTML 报告: {html_path}")

    return html_path


# ---------------------------------------------------------------------------
# 主入口
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    test_file = sys.argv[1] if len(sys.argv) > 1 else "tests/test_core_modules.py"

    print(f"🔬 运行测试: {test_file}")
    print("=" * 60)

    runner = DetailedTestRunner(test_file)
    result = runner.run()

    print(f"\n📊 {result['passed']}/{result['total']} passed in {result['duration']:.2f}s")
    print("=" * 60)

    output_dir = Path("reports")
    html_path = generate_detailed_report(result, output_dir)

    print(f"\n🌐 报告已生成，正在打开浏览器...")
